codecov
  require_ci_to_pass: yes
  
coverage:
  precision: 2
  round: down
  range: "0...100"
  
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      marco: no
      
comment:
  layout: "reach,diff,flags,tree"
  behavoir: default
  require_changes: no
