language: android
dist: trusty
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_EMULATOR_LEVEL=18
    - ANDROID_BUILD_TOOLS_VERSION= 29.0.3
    - ANDROID_ABI=armeabi-v7a 
    - ANDROID_BUILD_TIMEOUT= 20
    - ANDROID_TAG =Google_apis
    - QEMU_AUDIO_DRV = none
    
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMULATOR_LEVEL
  - extra-android-support
  - extra-google-m2reprository
  - extra-android-m2reprository
  - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMULATOR_LEVEL
 
 licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-licenses-.+
 
 before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"
 
 #before_script:
 # - android list target
 # - echo | no create adv --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
 # - emulator -adv test -no-window &
 # - android-wait-for-emulator
  
 #script:
 # - ./gradlew dependencyCheckAnalyze build
 # - adb shell input keyevent 82
 # - ./gradlew connectedCheck -PdisablePreDex --stacktrace
 
 before_script:
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
  
